### PR TITLE
[WIP] Add npm install to readme

### PR DESCRIPTION
**Pull request by johnthepink**

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
haha, much help. Totally forget this without Norma

**Comment by johnthepink** [comment]
@jbaxleyiii actually, that didn't fix it. getting this when runing `docker-compose up`

~~~
Error: Cannot find module 'mysql-live-select'
~~~

**Comment by jbaxleyiii** [comment]
boooo

**Comment by johnthepink** [comment]
@jbaxleyiii rebuilding worked. so this sequence for setup should be correct now

**Comment by jbaxleyiii** [comment]
It is correct

**Pull request merged**
