### PR TITLE
Sermons

### PR DESCRIPTION
**Pull request by johnthepink**
@jbaxleyiii i want to clean this up a little bit, but it works!

### CODE REVIEW

**Comment by johnthepink** [comment]
@jbaxleyiii i'm happy with this now. any thoughts?

**Comment by jbaxleyiii** [comment]
@johnthepink looks great. Thoughts on making schema pieces into helpers as well so we can share schema types  (like images)

**Comment by johnthepink** [comment]
@jbaxleyiii on it.

**Comment by johnthepink** [comment]
@jbaxleyiii this now includes image schemas, and abstracts images, media, and meta schemas to a helper.

**Comment by jbaxleyiii** [comment]
@johnthepink :trophy:

**Pull request merged**
